# Generated by Django 5.0.8 on 2024-08-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_in', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Checked out at'),
        ),
    ]
