# Generated by Django 5.0.8 on 2024-08-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Created'), (1, 'Invited'), (2, 'Accepted'), (3, 'Declined')], default=0, verbose_name='Status'),
        ),
    ]
