# Generated by Django 5.0.8 on 2024-08-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Tickie Administrator'), (1, 'Check In Security')], null=True, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='user',
            name='works_for_events',
            field=models.ManyToManyField(to='event.event', verbose_name='Works for events'),
        ),
    ]
