# Generated by Django 5.0.8 on 2024-08-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_works_for_events'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='works_for_events',
            field=models.ManyToManyField(blank=True, to='event.event', verbose_name='Works for events'),
        ),
    ]
